const OurFounders = {
  Heading: "Our Founder",
  Name: "PRABHAT KUMAR VERMA",
  SubHeading:
    "Teachers are the architect of society who carves the society without any endearment. ",
  Paragraph:
    "Teachers are the architect of society who carves the society without any endearment. The work of teacher is not only providing education but also to introduce the students into the knowledge of social circumstances. Shri Prabhat Kumar Verma, a Testile Engineer who was also a worthy teacher made a strong voice to give the right place to the teachers in this regard.Mr. Verma always said, 'The teacher is just like a lamp, that lights know ledge Teacher is just like a gardner who cultivates good qualities in taught. A teacher is just like a perfume who spreads the smell of education. Mr. Verma was born in an ordinary family on Ist August 1967 at Rajapur, Raebareli. The name of his father Sri Mathura Prasad Verma who is also a honourable teacher, Mr. Verma was very brilliant student from his childhood. He began to work as Textile Engineer after completing his higher education. Due to interest in education, he started out as a coaching at Anand Nagar, Racbareli which has been finally established at Arya Samaj Mandir, Khoya Mandi in 1999 with the lamp of Vibgyor Study Circle. Vibgyor Coaching soon took a huge turn due to his tireless efforts. Many qualified young men began to engage in teaching in this institute. His wife Smt. Vimla Verma who is a Govt. employee in District Industrial Centre, made great co-operation and encouragement in his work.Shri Verma also mastered in taking part in social work He became popular among people and the students call to him with name of Verma Ji le used to arrange free education, copy, book etc. to the poor students. In the mean time he established an Intermediate College in 2011 in village Chandauli, 5 Km. from Racharell. To maintain the work order, he resigned from spinning Mill in 2014 and totally engaged in teaching work. In the year of 2014 and 2015, many students illuminatd the name of district in the examination of Secondary & Higher Secondary exam. In the year of 2016, the college did what every institution imagined not only single student but three students named Km. Saumya Patel, achiesed Ist Position and Km. lqra & Umrah jointly achieved the 2nd position in High school examination conducted by U.P, Board secondary education. The recognition of the first school of the district at the State level and the ability to get the distinction in only 3 year could only be imagined by Verma Ji. Shri Verma ji, who spread the light of education in the district, died suddenly on the day of his birth on 1st August 2016 at the age of 49 years Everyone was in the ocean of sorrow and sadness. Today Shri Verma ji is not among us but the Plant planted by him has become a Whistle today, in whose camp thousands of families are being nourished. Such great man can not be described with the word of praise. The pen stops.Tears begin to flow from eyes. Chanting to such reputable personality."
};
export default OurFounders;
